### ISSUE TITLE
What CLion issue number is this hooked up to?

### ISSUE THREAD

**Issue by chrisdembia** [nbauernfeind/clion-syntax-highlighting-bug#1] opened 2015-02-13 20:55 UTC
I may have the same issue with the Zenburn theme. http://www.ideacolorthemes.org/themes/6/

**Comment by nbauernfeind** [comment] 2015-02-13 23:18
https://youtrack.jetbrains.com/issue/CPP-1063

Which was marked as a duplicate of https://youtrack.jetbrains.com/issue/CPP-53

**Closed as completed by nbauernfeind** 2015-02-13 23:18 UTC
